# Site settings
title: Richard Daniel (Words)
email: rdanieldesign@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of my day-to-day comments, conjectures, complaints and comparisons. I'm a blue-collar builder of the web.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rdanieldesign.github.io" # the base hostname & protocol for your site
twitter_username: rdaniel_design
github_username:  rdanieldesign

# Build settings
markdown: kramdown
